# Generated by Django 3.1 on 2020-09-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_twitteruser_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='display_name',
        ),
    ]
